### Data Visualisation on Netflix Dataset

In [1]:
import pandas as pd
import numpy as np

#### Credits DataSet

In [2]:
df = pd.read_csv('credits.csv')
df.head()

   person_id       id             name                character   role
0       3748  tm84618   Robert De Niro            Travis Bickle  ACTOR
1      14658  tm84618     Jodie Foster            Iris Steensma  ACTOR
2       7064  tm84618    Albert Brooks                      Tom  ACTOR
3       3739  tm84618    Harvey Keitel  Matthew 'Sport' Higgins  ACTOR
4      48933  tm84618  Cybill Shepherd                    Betsy  ACTOR

#### Titles Dataset

In [3]:
df1 = pd.read_csv('titles.csv')
df1.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7

#### Merging the Two Datasets Credits and Titles baaed on id

In [4]:
df = pd.merge(df,df1,on = 'id', how = 'inner')
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2

In [5]:
df.describe()

,person_id,release_year,runtime,seasons,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
count,7.721300e+04,77213.000000,77213.000000,13976.000000,72937.000000,7.285000e+04,77202.000000,76093.000000
mean,4.994603e+05,2014.921309,96.494425,2.073841,6.466389,5.871981e+04,27.791778,6.685284
std,6.128431e+05,8.132875,35.540358,2.269023,1.105710,1.553928e+05,67.365872,1.025811
min,7.000000e+00,1953.000000,0.000000,1.000000,1.500000,5.000000e+00,0.600000,1.000000
25%,4.158400e+04,2013.000000,83.000000,1.000000,5.800000,1.532000e+03,5.626000,6.000000
50%,1.829850e+05,2018.000000,100.000000,1.000000,6.500000,7.103000e+03,12.271000,6.700000
75%,8.415570e+05,2020.000000,118.000000,2.000000,7.300000,4.581000e+04,25.593000,7.400000
max,2.371585e+06,2022.000000,251.000000,42.000000,9.500000,2.268288e+06,1823.374000,10.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77213 entries, 0 to 77212
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   person_id             77213 non-null  int64
 1   id                    77213 non-null  object
 2   name                  77213 non-null  object
 3   character             67586 non-null  object
 4   role                  77213 non-null  object
 5   title                 77212 non-null  object
 6   type                  77213 non-null  object
 7   description           77160 non-null  object
 8   release_year          77213 non-null  int64
 9   age_certification     46595 non-null  object
 10  runtime               77213 non-null  int64
 11  genres                77213 non-null  object
 12  production_countries  77213 non-null  object
 13  seasons               13976 non-null  float64
 14  imdb_id               73388 non-null  object
 15  imdb_score            72937 non-null  float64
 16  imdb_votes            72850 non-null  float64
 17  tmdb_popularity       77202 non-null  float64
 18  tmdb_score            76093 non-null  float64
dtypes: float64(5), int64(3), object(11)
memory usage: 11.8+ MB

### Data Cleaning

#### Finding how many Null Values are there in dataset

In [7]:
df.isna().sum()

person_id                   0
id                          0
name                        0
character                9627
role                        0
title                       1
type                        0
description                53
release_year                0
age_certification       30618
runtime                     0
genres                      0
production_countries        0
seasons                 63237
imdb_id                  3825
imdb_score               4276
imdb_votes               4363
tmdb_popularity            11
tmdb_score               1120
dtype: int64

#### Replacing NA values in Character with 'Not Specified'

In [8]:
df["character"].fillna("Not Specified", inplace = True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2

#### Dropping the NA value in title

In [9]:
df.dropna(subset=['title'], inplace = True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2

#### Replacing NA values in Description with 'No Description'

In [10]:
df["description"].fillna("No Description", inplace = True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2

#### Filling NA values in age_certification with the method 'ffill'

In [11]:
df['age_certification'].fillna(method='ffill', inplace=True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2

#### Replacing NA values in seasons with most frequent values

In [12]:
df['seasons'].mode()

0    1.0
dtype: float64

In [13]:
df['seasons'].fillna(1,inplace = True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2

#### Replacing NA values in imdb_id with 'No IMDB_ID'

In [14]:
df['imdb_id'].fillna('No IMDB_ID',inplace = True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2

#### Replacing NA values in imdb_score with the median value of imdb_score

In [15]:
x = df['imdb_score'].median()
print(x)

6.5

In [16]:
df['imdb_score'].fillna(x, inplace = True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2

#### Replacing NA values in imdb_votes with the summation of min and max value

In [17]:
y = df['imdb_votes'].min() + df['imdb_votes'].max()
print(y)

2268293.0

In [18]:
df['imdb_votes'].fillna(y, inplace = True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2

#### Dropping NA values rows in tmdb_popularity

In [19]:
df.dropna(subset=['tmdb_popularity'], inplace = True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2

#### Filling NA values in tmdb_score with the method 'ffill'

In [20]:
df['tmdb_score'].fillna(method='ffill', inplace=True)
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],1.0,tt0075314,8.3,795222.0,27.612,8.2

In [21]:
df.isna().sum()

person_id               0
id                      0
name                    0
character               0
role                    0
title                   0
type                    0
description             0
release_year            0
age_certification       0
runtime                 0
genres                  0
production_countries    0
seasons                 0
imdb_id                 0
imdb_score              0
imdb_votes              0
tmdb_popularity         0
tmdb_score              0
dtype: int64

#### Getting unique values from the column 'genres'

In [22]:
type(df['genres'][1])

str

In [23]:
temp = list(set(df['genres'].values.tolist()))
temp

["['romance', 'action', 'crime', 'drama', 'thriller']",
 "['crime', 'family', 'comedy']",
 "['crime', 'thriller', 'action', 'european']",
 "['comedy', 'drama', 'crime', 'horror', 'action']",
 "['drama', 'thriller', 'crime', 'history']",
 "['crime', 'drama', 'history', 'thriller']",
 "['horror', 'crime']",
 "['comedy', 'crime', 'action']",
 "['thriller', 'fantasy', 'scifi', 'action', 'drama']",
 "['family', 'comedy', 'romance']",
 "['thriller', 'drama', 'action', 'crime']",
 "['action', 'family', 'animation', 'comedy']",
 "['comedy', 'family', 'action', 'drama']",
 "['romance', 'drama', 'action']",
 "['comedy', 'family', 'scifi', 'animation', 'action']",
 "['fantasy', 'comedy', 'family', 'action', 'drama']",
 "['comedy', 'family', 'sport']",
 "['drama', 'animation']",
 "['comedy', 'action', 'crime']",
 "['western', 'drama']",
 "['animation', 'romance', 'comedy', 'drama']",
 "['thriller', 'war', 'drama', 'action', 'scifi', 'european']",
 "['scifi', 'action', 'fantasy', 'animation']",
 "['thriller', 'scifi', 'action', 'european']",
 "['animation', 'action', 'drama']",
 "['drama', 'music', 'comedy', 'european']",
 "['horror', 'thriller', 'fantasy', 'war']",
 "['comedy', 'drama', 'crime']",
 "['family', 'fantasy', 'comedy']",
 "['crime', 'thriller', 'action']",
 "['documentation', 'crime', 'history', 'music']",
 "['fantasy', 'comedy', 'family', 'scifi', 'animation']",
 "['action', 'scifi', 'comedy', 'drama']",
 "['comedy', 'animation', 'family', 'fantasy', 'action']",
 "['drama', 'comedy', 'sport', 'reality']",
 "['thriller', 'history', 'drama']",
 "['drama', 'history', 'thriller', 'action', 'crime', 'european']",
 "['thriller', 'action', 'scifi']",
 "['horror', 'thriller', 'comedy']",
 "['comedy', 'family', 'animation', 'action']",
 "['comedy', 'scifi', 'animation', 'family', 'history']",
 "['horror', 'action']",
 "['horror', 'thriller', 'drama']",
 "['drama', 'animation', 'romance']",
 "['fantasy', 'romance', 'action', 'comedy', 'drama']",
 "['comedy', 'fantasy', 'reality']",
 "['comedy', 'drama', 'thriller', 'crime']",
 "['drama', 'comedy', 'scifi']",
 "['fantasy', 'animation', 'comedy', 'drama', 'family', 'scifi']",
 "['action', 'scifi', 'family', 'comedy', 'drama']",
 "['comedy', 'romance', 'family', 'drama']",
 "['scifi', 'action', 'drama', 'fantasy', 'animation']",
 "['thriller', 'action', 'horror']",
 "['comedy', 'animation', 'family', 'crime', 'european']",
 "['drama', 'romance', 'thriller', 'comedy']",
 "['scifi', 'animation', 'drama', 'fantasy', 'music', 'comedy', 'family']",
 "['action', 'horror', 'scifi', 'thriller', 'animation']",
 "['scifi', 'action', 'animation', 'comedy', 'fantasy']",
 "['western', 'action', 'crime', 'drama']",
 "['scifi', 'thriller', 'action', 'crime', 'drama']",
 "['thriller', 'crime', 'drama', 'action']",
 "['comedy', 'romance', 'documentation']",
 "['comedy', 'documentation', 'drama', 'european']",
 "['fantasy', 'action', 'animation']",
 "['family', 'animation', 'comedy', 'fantasy', 'western', 'action']",
 "['comedy', 'fantasy', 'animation', 'family', 'european']",
 "['comedy', 'documentation', 'reality']",
 "['western', 'horror', 'action']",
 "['thriller', 'comedy', 'crime', 'action', 'drama']",
 "['comedy', 'animation', 'family', 'scifi']",
 "['fantasy', 'horror', 'thriller', 'action']",
 "['drama', 'history', 'romance', 'war', 'documentation', 'comedy', 'european']",
 "['thriller', 'action', 'fantasy', 'scifi', 'comedy', 'drama']",
 "['scifi', 'horror', 'thriller', 'crime', 'drama', 'fantasy']",
 "['comedy', 'animation', 'family']",
 "['drama', 'fantasy', 'romance', 'animation']",
 "['comedy', 'drama', 'romance', 'family']",
 "['action', 'animation', 'drama', 'sport']",
 "['comedy', 'fantasy', 'animation', 'family', 'music', 'romance']",
 "['drama', 'comedy', 'thriller', 'fantasy', 'romance']",
 "['comedy', 'family', 'fantasy', 'animation', 'european']",
 "['drama', 'horror', 'thriller', 'european']",
 "['drama', 'action', 'crime']",
 "['crime', 'action', 'drama']",
 "['drama', 'crime', 'action', 'thriller']",
 "['comedy', 'thriller']",
 "['animation', 'action', 'scifi']",
 "['comedy', 'romance', 'drama']",
 "['comedy', 'animation', 'action', 'family', 'fantasy']",
 "['action', 'comedy', 'animation', 'family', 'fantasy']",
 "['drama', 'thriller', 'western', 'action', 'crime']",
 "['fantasy', 'drama', 'animation', 'action']",
 "['fantasy', 'action', 'family', 'scifi']",
 "['romance', 'comedy', 'scifi']",
 "['fantasy', 'family']",
 "['action', 'comedy', 'documentation']",
 "['action', 'war']",
 "['scifi', 'drama', 'animation', 'action', 'fantasy']",
 "['drama', 'sport', 'action']",
 "['action', 'comedy', 'crime']",
 "['drama', 'fantasy', 'action', 'history']",
 "['documentation', 'animation', 'european']",
 "['action', 'scifi', 'fantasy', 'drama']",
 "['horror', 'thriller']",
 "['fantasy', 'animation']",
 "['drama', 'action', 'thriller', 'romance']",
 "['horror', 'drama', 'fantasy', 'thriller', 'european']",
 "['horror']",
 "['comedy', 'action', 'animation', 'fantasy', 'thriller']",
 "['drama', 'family', 'music', 'comedy']",
 "['drama', 'war', 'animation', 'history', 'european']",
 "['comedy', 'fantasy', 'romance']",
 "['scifi', 'action', 'drama', 'fantasy', 'thriller', 'music']",
 "['comedy', 'sport', 'animation', 'action', 'family']",
 "['drama', 'documentation', 'fantasy', 'romance', 'scifi', 'family', 'animation']",
 "['action', 'crime', 'drama']",
 "['animation']",
 "['drama', 'fantasy', 'thriller', 'crime']",
 "['western', 'crime']",
 "['comedy', 'action', 'animation', 'fantasy']",
 "['thriller', 'crime', 'horror']",
 "['action', 'thriller', 'drama', 'scifi', 'horror', 'history']",
 "['crime', 'documentation', 'drama']",
 "['thriller', 'action', 'crime', 'western', 'european']",
 "['action', 'comedy', 'drama', 'family', 'scifi', 'animation']",
 "['action', 'animation', 'comedy', 'fantasy', 'history', 'scifi', 'war']",
 "['drama', 'romance', 'war', 'action']",
 "['crime', 'drama', 'thriller', 'european']",
 "['animation', 'comedy']",
 "['thriller', 'drama', 'fantasy', 'horror', 'scifi']",
 "['thriller', 'crime', 'romance', 'comedy', 'drama']",
 "['drama', 'action', 'comedy', 'fantasy', 'romance']",
 "['action', 'thriller', 'fantasy', 'horror', 'scifi']",
 "['scifi', 'comedy', 'drama', 'family', 'fantasy']",
 "['action', 'comedy', 'family', 'sport']",
 "['comedy', 'thriller', 'drama']",
 "['romance', 'drama', 'horror']",
 "['crime', 'drama', 'scifi']",
 "['drama', 'crime', 'sport']",
 "['animation', 'action', 'drama', 'family', 'fantasy']",
 "['fantasy', 'animation', 'family']",
 "['reality', 'action']",
 "['war', 'crime', 'drama', 'thriller']",
 "['comedy', 'fantasy', 'horror']",
 "['comedy', 'drama', 'european', 'romance']",
 "['scifi', 'animation', 'action', 'fantasy', 'horror']",
 "['fantasy', 'action', 'thriller']",
 "['fantasy', 'horror', 'drama']",
 "['comedy', 'family', 'documentation', 'animation']",
 "['crime', 'scifi', 'thriller', 'animation', 'action', 'comedy', 'european']",
 "['drama', 'crime', 'history', 'european']",
 "['drama', 'comedy', 'fantasy', 'music']",
 "['animation', 'fantasy']",
 "['history', 'documentation']",
 "['comedy', 'family', 'fantasy']",
 "['war', 'documentation', 'history']",
 "['drama', 'comedy', 'action', 'family', 'music']",
 "['comedy', 'family', 'drama', 'romance']",
 "['drama', 'sport', 'thriller']",
 "['thriller', 'crime', 'drama', 'scifi', 'action']",
 "['crime', 'drama']",
 "['drama', 'fantasy', 'romance']",
 "['comedy', 'crime', 'family', 'romance']",
 "['thriller', 'fantasy', 'horror', 'animation', 'comedy', 'drama', 'family']",
 "['drama', 'romance', 'thriller', 'action', 'comedy']",
 "['drama', 'thriller', 'reality']",
 "['drama', 'sport', 'action', 'crime']",
 "['action', 'comedy', 'european']",
 "['comedy', 'horror', 'reality', 'scifi']",
 "['scifi', 'action', 'fantasy', 'family']",
 "['scifi', 'drama', 'horror', 'thriller']",
 "['fantasy', 'comedy', 'drama', 'animation', 'action']",
 "['drama', 'crime', 'thriller', 'action', 'european']",
 "['romance', 'reality']",
 "['drama', 'family', 'documentation', 'sport']",
 "['western', 'thriller', 'action', 'crime', 'drama']",
 "['horror', 'thriller', 'documentation']",
 "['reality', 'documentation', 'comedy', 'history']",
 "['animation', 'thriller', 'history', 'drama', 'sport']",
 "['romance', 'crime', 'drama']",
 "['war', 'drama', 'action', 'thriller']",
 "['thriller', 'action']",
 "['drama', 'history', 'war', 'european']",
 "['drama', 'sport', 'thriller', 'action']",
 "['scifi', 'animation', 'action', 'drama', 'family', 'fantasy', 'comedy']",
 "['comedy', 'romance', 'scifi']",
 "['action', 'comedy', 'crime', 'drama', 'romance']",
 "['scifi', 'action', 'thriller']",
 "['family', 'fantasy', 'animation', 'comedy', 'european']",
 "['fantasy', 'comedy', 'family', 'animation', 'action']",
 "['action', 'crime', 'drama', 'romance']",
 "['scifi', 'fantasy', 'horror', 'thriller', 'family', 'music']",
 "['drama', 'thriller', 'comedy']",
 "['drama', 'thriller', 'comedy', 'crime', 'european']",
 "['thriller', 'comedy', 'crime', 'action']",
 "['documentation', 'drama', 'history', 'war', 'action']",
 "['scifi', 'comedy', 'thriller', 'drama', 'horror']",
 "['scifi', 'fantasy', 'action', 'family']",
 "['crime', 'thriller', 'scifi', 'drama', 'action']",
 "['thriller', 'horror', 'action']",
 "['animation', 'action', 'family', 'scifi', 'comedy']",
 "['reality', 'documentation', 'romance']",
 "['action', 'animation', 'comedy', 'drama', 'fantasy', 'romance']",
 "['thriller', 'action', 'comedy', 'crime']",
 "['scifi', 'family', 'fantasy', 'horror', 'thriller', 'drama']",
 "['action', 'family', 'comedy', 'drama']",
 "['scifi', 'action', 'family', 'fantasy', 'animation', 'comedy', 'drama']",
 "['comedy', 'scifi', 'action', 'animation', 'family', 'fantasy']",
 "['thriller', 'horror', 'comedy']",
 "['documentation', 'drama']",
 "['thriller', 'action', 'crime', 'drama']",
 "['drama', 'fantasy', 'thriller', 'action', 'comedy', 'scifi']",
 "['drama', 'romance', 'fantasy', 'comedy']",
 "['western', 'crime', 'drama', 'thriller']",
 "['romance', 'thriller', 'crime', 'drama']",
 "['documentation', 'european']",
 "['war', 'action', 'drama', 'thriller']",
 "['sport', 'drama']",
 "['thriller', 'crime', 'action', 'drama']",
 "['scifi', 'family', 'animation']",
 "['animation', 'action', 'drama', 'war']",
 "['comedy', 'music', 'action']",
 "['drama', 'war', 'action', 'history']",
 "['scifi', 'animation', 'action', 'drama']",
 "['drama', 'comedy', 'crime', 'romance', 'action']",
 "['fantasy', 'thriller', 'horror', 'drama', 'romance']",
 "['scifi', 'crime', 'fantasy', 'romance', 'comedy']",
 "['crime', 'scifi', 'thriller', 'drama', 'fantasy']",
 "['thriller', 'horror', 'crime', 'scifi']",
 "['action', 'scifi']",
 "['drama', 'romance', 'documentation']",
 "['animation', 'family', 'fantasy']",
 "['drama', 'sport']",
 "['comedy', 'thriller', 'romance', 'drama']",
 "['western', 'drama', 'history']",
 "['comedy', 'action', 'family', 'fantasy', 'sport']",
 "['drama', 'sport', 'european']",
 "['romance', 'documentation', 'drama', 'european']",
 "['action', 'comedy', 'crime', 'drama', 'animation']",
 "['fantasy', 'scifi', 'comedy', 'family', 'animation']",
 "['family', 'drama', 'sport']",
 "['animation', 'action', 'comedy', 'family']",
 "['action', 'comedy', 'animation', 'drama', 'fantasy']",
 "['comedy', 'fantasy', 'drama', 'crime']",
 "['war', 'action', 'drama', 'history']",
 "['action', 'thriller', 'crime', 'romance', 'drama']",
 "['documentation', 'drama', 'history']",
 "['thriller', 'action', 'crime', 'drama', 'sport']",
 "['drama', 'comedy', 'music']",
 "['scifi', 'action', 'drama', 'thriller', 'family']",
 "['drama', 'scifi', 'thriller']",
 "['war', 'drama', 'history', 'european']",
 "['action', 'fantasy', 'scifi', 'animation', 'comedy']",
 "['drama', 'action', 'crime', 'comedy']",
 "['comedy', 'documentation', 'music']",
 "['family', 'drama', 'war']",
 "['thriller', 'crime', 'drama', 'action', 'european']",
 "['war', 'fantasy', 'romance', 'action']",
 "['thriller', 'horror', 'fantasy']",
 "['drama', 'crime', 'fantasy', 'action', 'thriller']",
 "['documentation', 'family', 'drama']",
 "['comedy', 'romance', 'european']",
 "['comedy', 'horror', 'scifi', 'european']",
 "['thriller', 'scifi', 'drama', 'crime', 'action']",
 "['action', 'scifi', 'animation', 'fantasy']",
 "['scifi', 'fantasy', 'thriller', 'drama']",
 "['romance', 'drama', 'european']",
 "['thriller', 'fantasy', 'scifi', 'drama', 'romance']",
 "['horror', 'drama', 'thriller']",
 "['thriller', 'drama', 'scifi', 'european']",
 "['scifi', 'animation', 'comedy', 'drama']",
 "['comedy', 'action', 'romance']",
 "['action', 'scifi', 'horror']",
 "['action', 'animation', 'drama', 'thriller']",
 "['action', 'animation']",
 "['action', 'comedy', 'crime', 'drama']",
 "['action', 'drama', 'history', 'war']",
 "['drama', 'comedy', 'crime', 'history']",
 "['romance', 'family']",
 "['scifi', 'drama', 'romance', 'european']",
 "['comedy', 'romance', 'sport']",
 "['drama', 'comedy', 'crime', 'european']",
 "['comedy', 'drama', 'music', 'romance']",
 "['thriller', 'history', 'crime', 'drama', 'european']",
 "['action', 'drama', 'scifi', 'war', 'animation']",
 "['crime', 'documentation', 'drama', 'thriller']",
 "['horror', 'european']",
 "['comedy', 'crime', 'drama', 'family', 'animation', 'action']",
 "['drama', 'comedy']",
 "['drama', 'action', 'comedy']",
 "['comedy', 'drama', 'family', 'fantasy', 'animation', 'action']",
 "['romance', 'war', 'comedy', 'drama', 'european']",
 "['scifi', 'animation', 'action', 'comedy', 'drama', 'fantasy', 'romance', 'family']",
 "['comedy', 'crime', 'animation', 'action']",
 "['drama', 'romance', 'history', 'war']",
 "['drama', 'thriller', 'action']",
 "['documentation', 'drama', 'thriller']",
 "['documentation', 'drama', 'family', 'european']",
 "['fantasy', 'animation', 'comedy', 'drama', 'family']",
 "['drama', 'comedy', 'romance', 'thriller', 'crime']",
 "['scifi', 'comedy', 'family', 'fantasy', 'drama', 'animation', 'action']",
 "['drama', 'crime', 'romance']",
 "['fantasy', 'horror', 'thriller', 'action', 'comedy', 'drama']",
 "['scifi', 'drama', 'fantasy', 'thriller']",
 "['comedy', 'romance', 'thriller']",
 "['scifi', 'drama', 'fantasy', 'horror']",
 "['drama', 'action', 'crime', 'scifi', 'thriller']",
 "['scifi', 'comedy', 'romance', 'drama', 'fantasy']",
 "['scifi', 'fantasy', 'horror', 'action', 'drama']",
 "['comedy', 'animation', 'family', 'fantasy', 'scifi']",
 "['horror', 'scifi', 'thriller', 'drama']",
 "['scifi', 'animation', 'action', 'fantasy']",
 "['fantasy', 'animation', 'drama', 'family', 'comedy']",
 "['action', 'drama', 'crime']",
 "['action', 'scifi', 'comedy', 'family', 'animation']",
 "['drama', 'documentation', 'war']",
 "['documentation', 'war', 'history']",
 "['drama', 'action', 'fantasy']",
 "['scifi', 'action', 'fantasy', 'war', 'animation']",
 "['music', 'documentation', 'history', 'drama', 'european']",
 "['action', 'animation', 'drama', 'scifi', 'sport']",
 "['history']",
 "['comedy', 'reality']",
 "['family', 'comedy', 'drama']",
 "['action', 'family', 'comedy']",
 "['horror', 'thriller', 'action', 'crime', 'fantasy', 'european']",
 "['thriller', 'comedy', 'drama']",
 "['horror', 'scifi', 'thriller', 'european']",
 "['scifi', 'action', 'crime', 'drama', 'fantasy']",
 "['romance', 'action', 'comedy']",
 "['horror', 'comedy', 'european']",
 "['war', 'drama', 'history', 'romance', 'thriller', 'european']",
 "['scifi', 'animation', 'action', 'drama', 'war']",
 "['drama', 'thriller', 'european', 'romance']",
 "['fantasy', 'thriller', 'action', 'drama', 'family']",
 "['documentation', 'reality']",
 "['thriller', 'animation', 'fantasy', 'scifi', 'drama', 'family']",
 "['drama', 'documentation', 'comedy', 'romance']",
 "['western', 'drama', 'action', 'european']",
 "['romance', 'sport', 'comedy']",
 "['family', 'comedy']",
 "['thriller', 'drama', 'crime']",
 "['romance', 'drama', 'european', 'war']",
 "['fantasy', 'horror', 'thriller', 'family', 'drama', 'scifi']",
 "['romance', 'comedy', 'drama', 'music']",
 "['thriller', 'drama', 'history']",
 "['fantasy', 'drama', 'romance']",
 "['romance', 'family', 'comedy']",
 "['thriller', 'drama', 'family']",
 "['scifi', 'thriller', 'drama', 'european']",
 "['fantasy', 'family', 'comedy']",
 "['crime', 'drama', 'fantasy', 'scifi']",
 "['sport', 'documentation']",
 "['drama', 'action', 'comedy', 'crime', 'animation', 'documentation', 'family', 'fantasy']",
 "['romance', 'music', 'family']",
 "['drama', 'thriller', 'crime', 'fantasy']",
 "['horror', 'drama', 'fantasy', 'european']",
 "['horror', 'fantasy', 'scifi', 'action', 'thriller']",
 "['horror', 'thriller', 'fantasy']",
 "['action', 'scifi', 'thriller', 'drama']",
 "['thriller', 'action', 'drama', 'romance']",
 "['horror', 'thriller', 'animation', 'action', 'fantasy', 'comedy']",
 "['drama', 'thriller', 'comedy', 'crime']",
 "['drama', 'action', 'comedy', 'scifi']",
 "['romance', 'fantasy', 'horror']",
 "['action', 'crime', 'thriller', 'european']",
 "['music', 'family', 'fantasy']",
 "['action', 'animation', 'family', 'fantasy']",
 "['comedy', 'drama', 'action', 'scifi', 'animation']",
 "['drama', 'romance', 'thriller', 'fantasy', 'horror', 'scifi']",
 "['animation', 'comedy', 'fantasy']",
 "['drama', 'comedy', 'fantasy', 'romance']",
 "['drama', 'history', 'romance', 'war']",
 "['scifi', 'romance', 'drama']",
 "['animation', 'comedy', 'family', 'fantasy', 'scifi', 'action']",
 "['crime', 'scifi', 'drama', 'thriller', 'action', 'comedy']",
 "['animation', 'documentation']",
 "['animation', 'action', 'family']",
 "['fantasy', 'horror', 'scifi', 'thriller', 'action', 'drama']",
 "['documentation', 'crime', 'drama', 'thriller', 'war']",
 "['thriller', 'drama', 'romance', 'sport', 'european']",
 "['documentation', 'war']",
 "['fantasy', 'romance', 'family']",
 "['war', 'history', 'drama', 'romance', 'action']",
 "['scifi', 'comedy', 'fantasy', 'action']",
 "['action', 'scifi', 'animation', 'drama', 'fantasy']",
 "['comedy', 'drama', 'family', 'romance']",
 "['crime', 'history', 'documentation']",
 "['documentation', 'horror', 'reality']",
 "['documentation', 'comedy', 'history']",
 "['scifi', 'romance', 'animation', 'action', 'drama', 'fantasy', 'horror']",
 "['comedy', 'crime', 'drama', 'thriller']",
 "['crime', 'action', 'history']",
 "['thriller', 'western', 'action', 'drama', 'crime']",
 "['drama', 'war', 'thriller', 'horror']",
 "['animation', 'drama']",
 "['action', 'family', 'animation', 'history', 'scifi', 'romance', 'comedy', 'fantasy']",
 "['action', 'scifi', 'animation']",
 "['fantasy', 'scifi', 'action', 'comedy', 'family']",
 "['scifi', 'thriller', 'action', 'drama']",
 "['fantasy', 'animation', 'action', 'comedy', 'family', 'drama']",
 "['scifi', 'action', 'comedy', 'fantasy', 'animation', 'family']",
 "['comedy', 'horror', 'music']",
 "['drama', 'romance', 'music', 'european']",
 "['scifi', 'action', 'drama']",
 "['fantasy', 'action', 'scifi', 'thriller', 'comedy']",
 "['horror', 'animation', 'documentation', 'scifi', 'thriller', 'action', 'drama']",
 "['thriller', 'action', 'european']",
 "['drama', 'comedy', 'family', 'documentation']",
 "['action', 'thriller', 'drama', 'crime', 'romance']",
 "['drama', 'thriller', 'horror', 'scifi']",
 "['war', 'thriller']",
 "['drama', 'romance', 'music']",
 "['comedy', 'animation', 'drama']",
 "['scifi', 'family', 'fantasy', 'animation', 'action']",
 "['drama', 'animation', 'family', 'music']",
 "['thriller', 'action', 'comedy', 'crime', 'drama']",
 "['comedy', 'action', 'romance', 'family', 'drama']",
 "['crime', 'thriller', 'drama', 'action']",
 "['animation', 'european']",
 "['action', 'comedy', 'family', 'fantasy', 'animation', 'thriller', 'european']",
 "['scifi', 'thriller', 'drama', 'romance', 'comedy']",
 "['drama', 'war', 'action']",
 "['scifi', 'drama', 'fantasy', 'horror', 'animation', 'action']",
 "['drama', 'romance', 'horror', 'thriller']",
 "['drama', 'crime', 'action']",
 "['action', 'thriller', 'crime', 'european']",

In [24]:
l=[]
p=""
for i in range(len(temp)):
    x = temp[i]
    for j in x:
        if (j>='a' and j<='z') or (j>='A' and j<='Z'):
            p=p+j
        elif j==',' and p not in l:
            l.append(p)
            p=""
        elif p in l:
            p = ''
    if p not in l:
        l.append(p)
    p = ''
print(l)
print(len(l))

['romance', 'action', 'crime', 'drama', 'thriller', '', 'family', 'comedy', 'european', 'horror', 'history', 'fantasy', 'scifi', 'animation', 'sport', 'western', 'war', 'music', 'documentation', 'reality']
20

In [25]:
l.remove('')
len(l)

19

#### Creating columns for the unique genres based on genres value in the dataset

In [26]:
for i in range(len(l)):
    df[l[i]]=[1 if j.__contains__(l[i]) else 0 for j in df['genres']]

In [34]:
df.head()

,person_id,id,name,character,role,title,type,description,release_year,age_certification,...,history,fantasy,scifi,animation,sport,western,war,music,documentation,reality
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,...,0,0,0,0,0,0,0,0,0,0
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,...,0,0,0,0,0,0,0,0,0,0
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,...,0,0,0,0,0,0,0,0,0,0
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,...,0,0,0,0,0,0,0,0,0,0
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,...,0,0,0,0,0,0,0,0,0,0

#### Downloading the cleaned dataset

In [37]:
df.to_csv('cleaned.csv')

#### Dropping the columns 'description', 'genres'

In [38]:
df.drop(['description', 'genres'], axis=1, inplace = True)
df.head()

,person_id,id,name,character,role,title,type,release_year,age_certification,runtime,...,history,fantasy,scifi,animation,sport,western,war,music,documentation,reality
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,1976,R,113,...,0,0,0,0,0,0,0,0,0,0
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,1976,R,113,...,0,0,0,0,0,0,0,0,0,0
2,7064,tm84618,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,1976,R,113,...,0,0,0,0,0,0,0,0,0,0
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,1976,R,113,...,0,0,0,0,0,0,0,0,0,0
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,1976,R,113,...,0,0,0,0,0,0,0,0,0,0

In [39]:
df.isna().sum()

person_id               0
id                      0
name                    0
character               0
role                    0
title                   0
type                    0
release_year            0
age_certification       0
runtime                 0
production_countries    0
seasons                 0
imdb_id                 0
imdb_score              0
imdb_votes              0
tmdb_popularity         0
tmdb_score              0
romance                 0
action                  0
crime                   0
drama                   0
thriller                0
family                  0
comedy                  0
european                0
horror                  0
history                 0
fantasy                 0
scifi                   0
animation               0
sport                   0
western                 0
war                     0
music                   0
documentation           0
reality                 0
dtype: int64